import type { LucideIcon } from "lucide-react";
import {
  Apple,
  BadgePercent,
  Baby,
  Bike,
  Bird,
  Bone,
  BookOpen,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Building2,
  Bus,
  Camera,
  Car,
  CarFront,
  Cat,
  Circle,
  ClipboardList,
  Code,
  Cog,
  Coins,
  Cpu,
  Cross,
  Dog,
  DoorOpen,
  Drill,
  Dumbbell,
  Factory,
  FileText,
  Fish,
  Footprints,
  Gamepad2,
  Gem,
  Globe,
  GraduationCap,
  Hammer,
  HardHat,
  Heart,
  Home,
  HousePlus,
  Lamp,
  Landmark,
  Laptop,
  Leaf,
  Map,
  MonitorPlay,
  Music,
  Package,
  PackageCheck,
  PaintRoller,
  Palette,
  PartyPopper,
  PawPrint,
  Printer,
  Rabbit,
  Ruler,
  Shirt,
  Ship,
  Smartphone,
  Sofa,
  Sparkles,
  Tablet,
  Ticket,
  ToyBrick,
  Truck,
  Utensils,
  Warehouse,
  WashingMachine,
  Watch,
  Wrench,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "🚗": Car,
  "🏠": Home,
  "💼": Briefcase,
  "📱": Smartphone,
  "🛠️": Wrench,
  "🛋️": Sofa,
  cars: CarFront,
  motorcycles: Bike,
  parts: Cog,
  apartments: Building2,
  houses: HousePlus,
  commercial: Landmark,
  it: Code,
  sales: BadgePercent,
  logistics: Package,
  smartphones: Smartphone,
  laptops: Laptop,
  "tv-audio": MonitorPlay,
  repair: PaintRoller,
  education: GraduationCap,
  moving: PackageCheck,
  furniture: Lamp,
  appliances: WashingMachine,
  interior: Palette,
  apple: Apple,
  "badge-percent": BadgePercent,
  baby: Baby,
  bike: Bike,
  "bike-moto": Bike,
  bird: Bird,
  bone: Bone,
  "book-open": BookOpen,
  briefcase: Briefcase,
  briefcasebiz: BriefcaseBusiness,
  building: Building,
  "building-2": Building2,
  bus: Bus,
  camera: Camera,
  car: Car,
  "car-front": CarFront,
  cat: Cat,
  "clipboard-list": ClipboardList,
  code: Code,
  cog: Cog,
  coins: Coins,
  cpu: Cpu,
  cross: Cross,
  dog: Dog,
  "door-open": DoorOpen,
  drill: Drill,
  dumbbell: Dumbbell,
  factory: Factory,
  "file-text": FileText,
  fish: Fish,
  footprints: Footprints,
  "gamepad-2": Gamepad2,
  gem: Gem,
  globe: Globe,
  "graduation-cap": GraduationCap,
  hammer: Hammer,
  "hard-hat": HardHat,
  heart: Heart,
  home: Home,
  "house-plus": HousePlus,
  lamp: Lamp,
  landmark: Landmark,
  laptop: Laptop,
  leaf: Leaf,
  map: Map,
  "monitor-play": MonitorPlay,
  music: Music,
  package: Package,
  "package-check": PackageCheck,
  "paint-roller": PaintRoller,
  palette: Palette,
  "party-popper": PartyPopper,
  paw: PawPrint,
  printer: Printer,
  rabbit: Rabbit,
  ruler: Ruler,
  shirt: Shirt,
  ship: Ship,
  smartphone: Smartphone,
  sofa: Sofa,
  sparkles: Sparkles,
  tablet: Tablet,
  ticket: Ticket,
  "toy-brick": ToyBrick,
  trailer: Truck,
  truck: Truck,
  utensils: Utensils,
  warehouse: Warehouse,
  "washing-machine": WashingMachine,
  watch: Watch,
  wrench: Wrench,
};

export function CategoryIcon({ icon, className = "h-10 w-10", innerClassName = "h-5 w-5" }: { icon: string | null | undefined; className?: string; innerClassName?: string }) {
  const Icon = (icon ? ICONS[icon] : undefined) ?? Circle;

  return (
    <span
      className={`relative inline-flex shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-500 via-fuchsia-500 to-blue-600 text-white shadow-[inset_0_1px_0_rgba(255,255,255,0.6),0_10px_25px_rgba(79,70,229,0.35)] ${className}`}
      aria-hidden="true"
    >
      <span className="absolute inset-x-2 top-1 h-2 rounded-full bg-white/45 blur-[1px]" />
      <span className="absolute inset-0 rounded-2xl border border-white/30" />
      <Icon className={`relative drop-shadow-[0_2px_6px_rgba(15,23,42,0.45)] ${innerClassName}`} strokeWidth={2.25} />
    </span>
  );
}
